In [1]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
a = [(1,2,3),(4,5,6),(7,8,9)]
a

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [5]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.19182885, 0.9132626 ])

In [20]:
np.random.rand(2,3)

array([[0.11537086, 0.90370793, 0.35413143],
       [0.58664262, 0.94563189, 0.97446418]])

In [21]:
np.random.randn(2,3)

array([[ 0.38271632,  0.80381317,  1.4615962 ],
       [-0.54329783,  0.76575135,  0.73403745]])

In [25]:
np.random.randint(3,3333,4,)

array([ 812,  708,  298, 1323])

In [29]:
arr = np.arange(0,9)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
rand_arr = np.random.randint(0,60,10)

In [33]:
rand_arr

array([12, 37, 55, 14,  0,  1, 57, 17, 33, 31])

In [34]:
rand_arr.reshape(2,5)

array([[12, 37, 55, 14,  0],
       [ 1, 57, 17, 33, 31]])

In [35]:
rand_arr

array([12, 37, 55, 14,  0,  1, 57, 17, 33, 31])

In [36]:
max(rand_arr)

57

In [37]:
min(rand_arr)

0

In [39]:
rand_arr.argmax()

6

In [40]:
rand_arr.argmin()

4

In [41]:
rand_arr.shape

(10,)

In [43]:
rand_arr.dtype

dtype('int64')

# NumPy indexing and selection

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
arr[3]

3

In [46]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [47]:
arr[:3]

array([0, 1, 2])

In [48]:
arr[-2:5]

array([], dtype=int64)

In [49]:
arr[-1]

8

In [52]:
arr[0:3] = 199

In [54]:
arr

array([199, 199, 199, 199, 199, 199, 199, 199, 199])

In [55]:
array = np.arange(0,10)

In [56]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
slice_of_arr = array[1:5]

In [68]:
slice_of_arr

array([1, 2, 3, 4])

In [70]:
slice_of_arr[:] = 99

In [71]:
slice_of_arr

array([99, 99, 99, 99])

In [72]:
array

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [74]:
array_copy = array.copy()

In [76]:
array_copy[:] = 189 

In [77]:
array_copy

array([189, 189, 189, 189, 189, 189, 189, 189, 189, 189])

In [78]:
array

array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [84]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [98]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [99]:
arr_2d[1:,0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [100]:
array = np.arange(0,7)

In [101]:
array

array([0, 1, 2, 3, 4, 5, 6])

In [104]:
bol_array = array > 4

In [105]:
bol_array

array([False, False, False, False, False,  True,  True])

In [107]:
array[bol_array]

array([5, 6])

In [110]:
array_of_num = np.arange(0,50).reshape(5,10)

In [111]:
array_of_num

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [112]:
array_of_num[1:,0:3]

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

# NumPy Operations

In [113]:
arr = np.arange(0,11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [119]:
arr * 35

array([  0,  35,  70, 105, 140, 175, 210, 245, 280, 315, 350])

In [120]:
arr /5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [121]:
arr/0

/Users/maheshwarreddy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/maheshwarreddy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [122]:
array **2

array([ 0,  1,  4,  9, 16, 25, 36])

In [123]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974])

In [124]:
np.exp(array)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 , 403.42879349])

In [125]:
np.max( array)

6